import os
from pathlib import Path
from typing import Dict, Any, List
from datetime import datetime

from .config import REPORTS_DIR, DOCS_DIR

class OIReporter:
    """Generates deep institutional Markdown reports, interactive HTML dashboards, and CLI summaries."""

    def __init__(self):
        self.reports_dir = REPORTS_DIR
        self.docs_dir = DOCS_DIR

    def generate_markdown_report(self, analysis_result: Dict[str, Any], date_str: str) -> Path:
        """Generate comprehensive GitHub-flavored Markdown report with actionable intelligence."""
        weekly = analysis_result.get("weekly_analysis", {})
        monthly = analysis_result.get("monthly_analysis", {})
        shift = analysis_result.get("market_shift", {})
        playbook = weekly.get("playbook", {})

        symbol = weekly.get("symbol", "NIFTY")
        spot = weekly.get("underlying_price", 0.0)
        max_pain = weekly.get("max_pain", 0.0)
        totals = weekly.get("totals", {})
        atm_pcr = totals.get("atm_pcr_oi", 1.0)
        atm_pcr_chg = totals.get("atm_pcr_chg_oi", 1.0)
        tot_pcr = totals.get("pcr_oi", 1.0)
        regime = playbook.get("regime", "NEUTRAL").replace("_", " ")
        sr = weekly.get("sr_levels", {})

        md = []
        md.append(f"# 🧠 {symbol} EOD Smart Money & Directional Shift Intelligence")
        md.append(f"**Date:** `{date_str}` | **Market Close:** `{weekly.get('timestamp')}` | **Weekly Expiry:** `{weekly.get('expiry')}` | **Monthly Expiry:** `{monthly.get('expiry')}`\n")

        # Actionable Shift Banner
        shift_headline = shift.get("headline", "Market Analysis Active")
        md.append(f"> ### {shift_headline}\n")

        # Visual Intelligence Card
        md.append("## 📈 Executive Intelligence Card")
        md.append("![EOD Smart Money OI Intelligence Card](latest_oi_chart.png)\n")

        # Institutional Playbook
        md.append("## 🎯 Institutional Playbook & Action Plan for Next Session")
        md.append(f"**Market Regime:** `{regime}` — *{playbook.get('regime_desc', '')}*\n")
        md.append("| Tactical Component | Strategy & Trade Trigger |")
        md.append("| :--- | :--- |")
        md.append(f"| 🟢 **Bullish Trigger** | **{playbook.get('bullish_trigger')}** |")
        md.append(f"| 🔴 **Bearish Trigger** | **{playbook.get('bearish_trigger')}** |")
        md.append(f"| ⚖️ **Straddle Corridor** | **{playbook.get('range_play')}** |")
        md.append(f"| 🎯 **Expected Expiry Band** | **`{playbook.get('expected_range')}`** (ATM Straddle: `{weekly.get('atm_straddle', {}).get('premium', 0):.1f}` pts) |")
        md.append(f"| 🛡️ **Major Support Floor (S1)** | **`{sr.get('support_1'):,.0f}`** (Highest Put OI concentration) |")
        md.append(f"| 🧱 **Major Resistance Wall (R1)** | **`{sr.get('resistance_1'):,.0f}`** (Highest Call OI concentration) |\n")

        # Trapped Writers & Positioning Analysis
        md.append("### ⚡ Trapped Writers & Smart Money Footprint")
        for line in playbook.get("trapped_writers", []):
            md.append(f"- **Risk Alert:** {line}")
        md.append(f"- **Actionable ATM Battleground PCR (ATM ±10):** `{atm_pcr:.2f}` *(Unpolluted by far OTM hedge skew)*")
        md.append(f"- **Intraday Additions PCR (ATM ±10):** `{atm_pcr_chg:.2f}` *(Where fresh margin was deployed today)*")
        md.append(f"- **Full Chain PCR:** `{tot_pcr:.2f}` *(Included for reference; contains far OTM wing hedges)*\n")

        # Day-over-Day Shift Metrics
        if shift.get("has_previous_data"):
            md.append("### 🔄 Day-over-Day Migration")
            for d in shift.get("details", []):
                md.append(f"- {d}")
            md.append("")

        # Weekly vs Monthly Perspective
        m_pcr = monthly.get("totals", {}).get("atm_pcr_oi", monthly.get("totals", {}).get("pcr_oi", 1.0))
        m_regime = monthly.get("playbook", {}).get("regime", monthly.get("sentiment", {}).get("verdict", "NEUTRAL")).replace("_", " ")
        md.append("### 🗓️ Tactical Weekly vs Structural Monthly Alignment")
        md.append(f"- **Weekly Tactical View ({weekly.get('expiry')}):** `{regime}` (ATM PCR: `{atm_pcr:.2f}`)")
        md.append(f"- **Monthly Structural View ({monthly.get('expiry')}):** `{m_regime}` (ATM PCR: `{m_pcr:.2f}`)")
        if regime == m_regime:
            md.append(f"- **Alignment:** Weekly and Monthly trends are **congruent ({regime})**, reinforcing trend durability.")
        else:
            md.append(f"- **Alignment:** **Tactical divergence detected** between weekly momentum (`{regime}`) and monthly backdrop (`{m_regime}`). Anticipate chop at S1/R1 boundaries.")
        md.append("")

        md.append("\n---\n*Auto-generated by EOD OI Analysis Engine with browser TLS impersonation via curl_cffi. Full strike heatmap available in the HTML dashboard.*")

        content = "\n".join(md)

        # Save dated report and latest.md
        dated_path = self.reports_dir / f"EOD_OI_ANALYSIS_{date_str}.md"
        latest_path = self.reports_dir / "latest.md"

        with open(dated_path, "w", encoding="utf-8") as f:
            f.write(content)
        with open(latest_path, "w", encoding="utf-8") as f:
            f.write(content)

        return dated_path

    def generate_html_dashboard(self, analysis_result: Dict[str, Any], history: List[Dict[str, Any]]) -> Path:
        """Create responsive GitHub Pages HTML dashboard in docs/index.html."""
        weekly = analysis_result.get("weekly_analysis", {})
        monthly = analysis_result.get("monthly_analysis", {})
        shift = analysis_result.get("market_shift", {})
        playbook = weekly.get("playbook", {})

        symbol = weekly.get("symbol", "NIFTY")
        spot = weekly.get("underlying_price", 0.0)
        max_pain = weekly.get("max_pain", 0.0)
        totals = weekly.get("totals", {})
        atm_pcr = totals.get("atm_pcr_oi", 1.0)
        atm_pcr_chg = totals.get("atm_pcr_chg_oi", 1.0)
        regime = playbook.get("regime", "NEUTRAL").replace("_", " ")
        badge_color = playbook.get("color", "#f59e0b")
        shift_headline = shift.get("headline", "Market direction analysis active")
        sr = weekly.get("sr_levels", {})

        atm_strike = weekly.get("atm_strike", spot)
        atm_window = weekly.get("atm_window_strikes", [])
        focused_strikes = [s for s in atm_window if abs(s["strikePrice"] - atm_strike) <= (8 * 50)]
        focused_strikes.sort(key=lambda x: x["strikePrice"])

        # Strike rows
        strike_rows_html = []
        for s in focused_strikes:
            strike = s["strikePrice"]
            is_atm = strike == atm_strike
            row_class = "atm-row" if is_atm else ""
            badge_atm = '<span class="badge badge-atm">ATM</span>' if is_atm else ""
            c_oi = f"{s['ce_oi']/100000:.2f}"
            c_chg = f"{s['ce_chg_oi']/100000:+.2f}"
            c_chg_class = "text-danger" if s["ce_chg_oi"] > 0 else ("text-success" if s["ce_chg_oi"] < 0 else "")
            p_oi = f"{s['pe_oi']/100000:.2f}"
            p_chg = f"{s['pe_chg_oi']/100000:+.2f}"
            p_chg_class = "text-success" if s["pe_chg_oi"] > 0 else ("text-danger" if s["pe_chg_oi"] < 0 else "")

            strike_rows_html.append(f"""
            <tr class="{row_class}">
                <td>{c_oi}</td>
                <td class="{c_chg_class}">{c_chg}</td>
                <td><span class="badge badge-subtle">{s['ce_buildup']}</span></td>
                <td class="strike-val">{strike:,.0f} {badge_atm}</td>
                <td><span class="badge badge-subtle">{s['pe_buildup']}</span></td>
                <td class="{p_chg_class}">{p_chg}</td>
                <td>{p_oi}</td>
            </tr>
            """)

        # History rows
        hist_rows_html = []
        for h in reversed(history[-7:]):
            hist_rows_html.append(f"""
            <tr>
                <td>{h.get('date')}</td>
                <td><b>{h.get('underlying_price', 0):,.2f}</b></td>
                <td>{h.get('weekly_pcr_oi', 1.0):.2f}</td>
                <td>{h.get('weekly_max_pain', 0):,.0f}</td>
                <td>{h.get('weekly_support_1', 0):,.0f} - {h.get('weekly_resistance_1', 0):,.0f}</td>
                <td><span class="badge badge-subtle">{h.get('weekly_sentiment', 'N/A')}</span></td>
            </tr>
            """)

        html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{symbol} EOD Smart Money OI Intelligence</title>
    <style>
        :root {{
            --bg: #0b0f19;
            --surface: #111827;
            --surface-elevated: #1f2937;
            --border: #374151;
            --text: #f9fafb;
            --text-muted: #9ca3af;
            --accent: #38bdf8;
            --success: #10b981;
            --danger: #ef4444;
            --warning: #f59e0b;
        }}
        * {{ box-sizing: border-box; margin: 0; padding: 0; }}
        body {{
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
            background-color: var(--bg);
            color: var(--text);
            line-height: 1.5;
            padding: 24px;
        }}
        .container {{ max-width: 1300px; margin: 0 auto; }}
        header {{
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 24px;
            padding-bottom: 16px;
            border-bottom: 1px solid var(--border);
        }}
        h1 {{ font-size: 24px; font-weight: 700; }}
        .meta {{ color: var(--text-muted); font-size: 14px; margin-top: 4px; }}
        .banner {{
            background: linear-gradient(135deg, rgba(31, 41, 55, 0.9), rgba(17, 24, 39, 0.9));
            border-left: 4px solid {badge_color};
            border-radius: 8px;
            padding: 16px 20px;
            margin-bottom: 24px;
            font-size: 16px;
            font-weight: 600;
        }}
        .grid {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(210px, 1fr));
            gap: 16px;
            margin-bottom: 24px;
        }}
        .card {{
            background: var(--surface);
            border: 1px solid var(--border);
            border-radius: 10px;
            padding: 18px;
        }}
        .card-label {{ font-size: 12px; text-transform: uppercase; color: var(--text-muted); letter-spacing: 0.05em; }}
        .card-value {{ font-size: 24px; font-weight: 700; margin-top: 6px; }}
        .badge {{
            display: inline-block;
            padding: 4px 10px;
            border-radius: 9999px;
            font-size: 12px;
            font-weight: 600;
        }}
        .badge-verdict {{ background: {badge_color}; color: #000; }}
        .badge-atm {{ background: var(--accent); color: #000; margin-left: 6px; }}
        .badge-subtle {{ background: var(--surface-elevated); color: var(--text-muted); font-size: 11px; }}
        .playbook-box {{
            background: var(--surface);
            border: 1px solid var(--border);
            border-radius: 10px;
            padding: 20px;
            margin-bottom: 24px;
        }}
        .playbook-grid {{
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 16px;
            margin-top: 14px;
        }}
        .trigger-card {{
            background: var(--surface-elevated);
            border-radius: 8px;
            padding: 14px;
            border-left: 4px solid var(--border);
        }}
        .trigger-bull {{ border-left-color: var(--success); }}
        .trigger-bear {{ border-left-color: var(--danger); }}
        .chart-box {{
            background: var(--surface);
            border: 1px solid var(--border);
            border-radius: 10px;
            padding: 20px;
            margin-bottom: 24px;
            text-align: center;
        }}
        .chart-box img {{ max-width: 100%; height: auto; border-radius: 6px; }}
        table {{
            width: 100%;
            border-collapse: collapse;
            font-size: 13px;
        }}
        th, td {{
            padding: 10px 12px;
            text-align: center;
            border-bottom: 1px solid var(--border);
        }}
        th {{ background: var(--surface-elevated); color: var(--text-muted); font-weight: 600; }}
        tr:hover {{ background: rgba(255, 255, 255, 0.02); }}
        .atm-row {{ background: rgba(56, 189, 248, 0.12) !important; font-weight: 600; }}
        .strike-val {{ font-weight: 700; color: var(--text); }}
        .text-success {{ color: var(--success); font-weight: 600; }}
        .text-danger {{ color: var(--danger); font-weight: 600; }}
        footer {{
            text-align: center;
            color: var(--text-muted);
            font-size: 13px;
            margin-top: 36px;
            padding-top: 20px;
            border-top: 1px solid var(--border);
        }}
        @media (max-width: 768px) {{
            .playbook-grid {{ grid-template-columns: 1fr; }}
        }}
    </style>
</head>
<body>
    <div class="container">
        <header>
            <div>
                <h1>🧠 {symbol} EOD Smart Money OI Intelligence</h1>
                <div class="meta">NSE Official v3 API &bull; Weekly Expiry: {weekly.get('expiry')} &bull; Close: {weekly.get('timestamp')}</div>
            </div>
            <div>
                <span class="badge badge-verdict">{regime}</span>
            </div>
        </header>

        <div class="banner">
            {shift_headline}
        </div>

        <div class="grid">
            <div class="card">
                <div class="card-label">Spot Price</div>
                <div class="card-value" style="color: var(--accent);">{spot:,.2f}</div>
            </div>
            <div class="card">
                <div class="card-label">Max Pain</div>
                <div class="card-value" style="color: var(--warning);">{max_pain:,.0f}</div>
            </div>
            <div class="card">
                <div class="card-label">Actionable ATM PCR (±10)</div>
                <div class="card-value" style="color: {'var(--success)' if atm_pcr >= 1.0 else 'var(--danger)'};">{atm_pcr:.2f}</div>
            </div>
            <div class="card">
                <div class="card-label">ATM Chg PCR (Intraday)</div>
                <div class="card-value" style="color: {'var(--success)' if atm_pcr_chg >= 1.0 else 'var(--danger)'};">{atm_pcr_chg:.2f}</div>
            </div>
            <div class="card">
                <div class="card-label">Expected Expiry Band</div>
                <div class="card-value" style="font-size: 18px;">{playbook.get('expected_range', 'N/A')}</div>
            </div>
        </div>

        <div class="playbook-box">
            <h3>🎯 Tactical Playbook & Trade Setups for Next Session</h3>
            <p style="margin-top: 6px; color: var(--text-muted); font-size: 14px;">{playbook.get('smart_money_verdict', '')}</p>
            <div class="playbook-grid">
                <div class="trigger-card trigger-bull">
                    <div style="font-size: 11px; text-transform: uppercase; color: var(--success); font-weight: 700;">🟢 Bullish Confirmation Trigger</div>
                    <div style="margin-top: 6px; font-weight: 600;">{playbook.get('bullish_trigger', '')}</div>
                </div>
                <div class="trigger-card trigger-bear">
                    <div style="font-size: 11px; text-transform: uppercase; color: var(--danger); font-weight: 700;">🔴 Bearish Breakdown Trigger</div>
                    <div style="margin-top: 6px; font-weight: 600;">{playbook.get('bearish_trigger', '')}</div>
                </div>
            </div>
        </div>

        <div class="chart-box">
            <h3 style="margin-bottom: 16px; text-align: left;">📊 Executive Market Intelligence Card</h3>
            <img src="latest_oi_chart.png" alt="EOD OI Intelligence Card">
        </div>

        <div class="card" style="margin-bottom: 24px; overflow-x: auto;">
            <h3 style="margin-bottom: 16px;">🎯 Strike-by-Strike Buildup (Actionable ATM Battleground)</h3>
            <table>
                <thead>
                    <tr>
                        <th>Call OI (L)</th>
                        <th>Call Chg OI (L)</th>
                        <th>Call Buildup</th>
                        <th>Strike</th>
                        <th>Put Buildup</th>
                        <th>Put Chg OI (L)</th>
                        <th>Put OI (L)</th>
                    </tr>
                </thead>
                <tbody>
                    {''.join(strike_rows_html)}
                </tbody>
            </table>
        </div>

        <div class="card" style="margin-bottom: 24px; overflow-x: auto;">
            <h3 style="margin-bottom: 16px;">🗓️ Recent Historical Snapshots</h3>
            <table>
                <thead>
                    <tr>
                        <th>Date</th>
                        <th>Spot Close</th>
                        <th>ATM PCR</th>
                        <th>Max Pain</th>
                        <th>Range (S1 - R1)</th>
                        <th>Verdict</th>
                    </tr>
                </thead>
                <tbody>
                    {''.join(hist_rows_html)}
                </tbody>
            </table>
        </div>

        <footer>
            Automated NSE EOD Open Interest Analyzer &bull; Hosted on GitHub Pages &bull; Powered by curl_cffi & Python
        </footer>
    </div>
</body>
</html>
"""
        html_file = self.docs_dir / "index.html"
        with open(html_file, "w", encoding="utf-8") as f:
            f.write(html_content)

        return html_file

    def print_cli_summary(self, analysis_result: Dict[str, Any]) -> None:
        """Concise, high-impact terminal summary."""
        weekly = analysis_result.get("weekly_analysis", {})
        monthly = analysis_result.get("monthly_analysis", {})
        shift = analysis_result.get("market_shift", {})
        playbook = weekly.get("playbook", {})

        spot = weekly.get("underlying_price", 0.0)
        max_pain = weekly.get("max_pain", 0.0)
        totals = weekly.get("totals", {})
        atm_pcr = totals.get("atm_pcr_oi", 1.0)
        atm_pcr_chg = totals.get("atm_pcr_chg_oi", 1.0)
        regime = playbook.get("regime", "NEUTRAL")
        sr = weekly.get("sr_levels", {})

        print("\n" + "="*72)
        print(f"  {weekly.get('symbol')} EOD SMART MONEY & SHIFT INTELLIGENCE")
        print("="*72)
        print(f"  Market Close       : {weekly.get('timestamp')}")
        print(f"  Spot Price         : {spot:,.2f}")
        print(f"  Max Pain Strike    : {max_pain:,.0f}")
        print(f"  Actionable ATM PCR : {atm_pcr:.2f} (Chg PCR: {atm_pcr_chg:.2f})")
        print(f"  Expected Expiry Band: {playbook.get('expected_range')}")
        print(f"  Major Support (S1) : {sr.get('support_1'):,.0f} (Highest Put OI Wall)")
        print(f"  Major Resistance(R1): {sr.get('resistance_1'):,.0f} (Highest Call OI Wall)")
        print(f"  Tactical Regime    : {regime}")
        print(f"  [+] Bull Trigger   : {playbook.get('bullish_trigger')}")
        print(f"  [-] Bear Trigger   : {playbook.get('bearish_trigger')}")
        print("="*72 + "\n")
